# frozen_string_literal: true

require 'rake/testtask'
require_relative '../src/accuracy_reporter'
require_relative '../src/data_trainer'

task default: :test

desc 'Export the accuracy score report to Botpress'
Rake::Task.define_task(:export_accuracy_report) do
  scheme    = 'https'
  host      = 'oasist-botpress-server.herokuapp.com'
  bot_id    = 'sample-bot'
  user_id   = 'oasist'
  dirname   = File.join('..', 'csv')
  test_data = File.join(dirname, 'test_data.csv')

  AccuracyReporter.run(scheme:, host:, bot_id:, user_id:, test_data:, dirname:)
  puts "--- Successfully exported accuracy score chart under #{dirname}/ ---"
end

desc 'Convert the CSV test data to JSON format and export'
Rake::Task.define_task(:convert_test_data) do
  csv_training_data = File.join('..', 'csv', 'training_data.csv')
  dirname           = File.join('..', 'json')

  data_trainer = DataTrainer.new(csv_training_data)
  data_trainer.export(dirname)
  puts "--- Successfully exported JSON training data under #{dirname}/ ---"
end

desc 'Run all tests'
Rake::TestTask.new do |task|
  task.pattern = File.join('.', '**', '*_test.rb')
end
