# frozen_string_literal: true

require 'rake/testtask'
require_relative 'src/accuracy_reporter'
require_relative 'src/training_data_formatter'

task default: :test

desc 'Export the accuracy score report to Botpress'
Rake::Task.define_task(:export_accuracy_report) do
  scheme    = 'https'
  host      = 'oasist-botpress-server.herokuapp.com'
  bot_id    = 'sample-bot'
  user_id   = 'oasist'
  dirname   = File.join('..', 'csv')
  test_data = File.join(dirname, 'test_data.csv')

  AccuracyReporter.run(scheme:, host:, bot_id:, user_id:, test_data:, dirname:)
  puts "--- Successfully exported accuracy score chart under #{dirname}/ ---"
end

desc 'Format the CSV test data to JSON and export'
Rake::Task.define_task(:format_test_data) do
  csv_training_data = File.join('..', 'csv', 'training_data.csv')
  dirname           = File.join('..', 'json')

  training_data_formatter = TrainingDataFormatter.new(csv_training_data)
  training_data_formatter.export(dirname)
  puts "--- Successfully exported JSON training data under #{dirname}/ ---"
end

desc 'Run all tests'
Rake::TestTask.new do |task|
  task.pattern = File.join('.', '**', '*_test.rb')
end
